name: job_pro
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_swiper : ^1.1.6
  carousel_slider: ^1.3.0
  badges: ^1.1.0
  http: ^0.12.0+2
  font_awesome_flutter: ^8.5.0
  fluttertoast: ^8.0.8
  custom_radio: ^0.1.2
  page_transition: "^1.1.5"
  flutter_spinkit: ^3.1.0
  bubble_bottom_bar: ^1.2.0
  flutter_slidable: "^0.5.4"
  custom_switch: 
  simple_animations: ^1.3.4
  flutter_xlider: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon.png
    - assets/user_profile/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans/OpenSans-Regular.ttf
        - asset: fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 500
